theme: jekyll-theme-minimal
title: [Retro Randonneurs]
logo: /media/retro-randonneurs-logo.png
description: [On this page you can follow the restoration progress on an old bike. The aim is to create a _Retro Randonneur_ bike.
]